### ISSUE TITLE
Application can't provide results

### ISSUE THREAD

**Issue by dgubarev** [kelevra13/ctco-homework#1]
Hello Vadim!

Application is runnable, but not working.
Test Scenario:
1. Press '1' if you want to create a friend, and fill his list of expenses.
    Enter: 1
2. Enter person name:
    Enter: Vadim
3. Button - 1: save to list.
    Enter: 1
4. Enter your expenses:
    Enter: 100
5. Application doing nothing. Application is running, but no any results are printed.

P.S: Please fix it and then contact with us. 
Also please add some test scenario to the Readme file.

Screenshot: 
![test scenario](https://cloud.githubusercontent.com/assets/7290350/15700092/91c06464-27da-11e6-9032-95c6a5b44de8.PNG)

**Comment by kelevra13** [comment]
Hello!

It's all work, but I just forgot to write that in first of all need to
enter service, and only then price!
For example: Hotel - press enter - 120 - press enter.
It's because I'm using HashMap, to contains and service and price in one
place!
And the last question, excuse me, but what about test scenarion you
talking? Just to run this application on my device, and put the result in
the Readme file?

Best regards, Vadim.




2016-06-01 9:21 GMT+03:00 dgubarev <notifications@github.com>:

**Comment by kelevra13** [comment]
I'm understood it all, and fixed it already!
Test scenario was attached to Readme file.

2016-06-01 10:16 GMT+03:00 Вадим Рожкалнс <vadim.rozhkalns@gmail.com>:

**Comment by dgubarev** [comment]
Thanks, Application is working fine. Readme is OK too.
